[package]
name = "reverse-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = { version = "0.38.0", features = ["redis_tokio"] }
fast-socks5 = "0.8.0"
futures = "0.3.23"
hyper = { version = "0.14.20", features = ["full"] }
hyper-tungstenite = "0.8.1"
lazy_static = "1.4.0"
reqwest = { version = "0.11.11", features = ["socks"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.17.2"
tungstenite = "0.17.3"
url = "2.2.2"

[build-dependencies]
minify-html = "0.9.2"
