[package]
name = "reverse-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = { version = "0.38.0", features = ["redis_tokio"] }
dotenv = "0.15.0"
fast-socks5 = "0.8.0"
futures-util = "0.3.23"
hyper = { version = "0.14.20", features = ["server", "http1", "http2"] }
hyper-tungstenite = "0.8.1"
lazy_static = "1.4.0"
postgrest = "1.3.1"
reqwest = { version = "0.11.11", features = ["socks", "json"] }
serde = "1.0.143"
serde_json = "1.0.83"
thiserror = "1.0.32"
tokio = { version = "1" }
tokio-tungstenite = "0.17.2"
tungstenite = "0.17.3"
url = "2.2.2"

[build-dependencies]
minify-html = "0.9.2"
